### ISSUE TITLE
Pas de remontés d'informations.

### ISSUE THREAD

**Issue by gillesdubois** [PluginsOCSInventory-NG/uptime#1]
De @headquaker :
Je n'ai pas les informations qui apparaissent dans OCS alors que pour Office c'est bon.
En local via une commande /local /xml /debug=2 j'ai bien les information.

**Comment by gillesdubois** [comment]
Bonjour,

Les informations uptime apparaissent dans l'onglet "Divers" des informations inventaire des ordinateurs.

Avez-vous redémarré le service apache après l'installation du plugin ? sur certains système le redémarrage du service est necéssaire.

Une déconnexion / reconnexion a l'interface peut aussi être utile.

Cordialement,
Gilles Dubois.

**Comment by headquaker** [comment]
Oui j'ai déjà fait tout ça.

J'ai seulement winusers et le plug office qui fonctionnent.

J'ai regardé un peu plus en profondeur.

Les tables dans la BDD semblent toutes dispo.
Par contre il n'y a rien dans les tables du coup je me demande si ce n'est pas un problème d'insert.

Le vbs renvoie bien les infos.

**Comment by gillesdubois** [comment]
Le plugin a t-il été téléchargé a cette adresse ? https://github.com/PluginsOCSInventory-NG/uptime/releases/download/1.0/uptime.zip
Avez-vous pris le bon vbs ? celui qui es dans le zip de release dans le repertoire AGENT ?

La méthode d'insert est la même pour tout les plugins, si elle marche pas un elle doit marcher pour les autres.

**Comment by headquaker** [comment]
- Le plugin a t-il été téléchargé a cette adresse ? https://github.com/PluginsOCSInventory-NG/uptime/releases/download/1.0/uptime.zip -> OUI
- Avez-vous pris le bon vbs ? celui qui es dans le zip de release dans le repertoire AGENT ? -> OUI

**Comment by headquaker** [comment]
Un log:

==============================================================================
Starting OCS Inventory NG Agent on Thursday, February 18, 2016 15:42:48.
AGENT => Running OCS Inventory NG Agent Version 2.1.0.1
AGENT => Using OCS Inventory NG FrameWork Version 2.1.0.1
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) succesfully loaded on 0 DLL(s) found
AGENT => Local mode actived by /LOCAL argument: No network connection
	DID_CHECK => Read DeviceID <PO-DEP2-2016-02-18-13-05-03> and MACs <F8:CA:B8:16:F0:7318:5E:0F:2C:41:0600:A0:C6:00:00:141A:5E:0F:2C:41:071A:5E:0F:2C:41:0654:61:02:63:8F:12> in file <ocsinventory.dat>
AGENT => Sending Prolog
	LOCAL => Writing compressed XML file <C:\ProgramData\OCS Inventory NG\Agent\PO-DEP2-2016-02-18-13-05-03.ocs> required by argument /LOCAL
================= TRACE START ===============
<?xml version="1.0" encoding="UTF-8"?>

<REPLY>
<RESPONSE>SEND</RESPONSE>
</REPLY>


================= TRACE STOP ===============
AGENT => Prolog successfully sent
SUPPORT => No support detected, Registration key : N/A
ERROR *** AGENT => Failed to write Prolog Frequency <Error code 32 = Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.  >
AGENT => Inventory required
AGENT => Launching hardware and software checks
	INVENTORY => Loading Download history
	INVENTORY => Logged on user ID is <gemensoif>
	INVENTORY => Operating System is <Microsoft Windows 7 Entreprise 6.1.7601 Service Pack 1>, description <>
	INVENTORY => Operating System uses 32 bits memory address width
	INVENTORY => Computer domain or workgroup is <nt.florette.com>
	INVENTORY => User domain is <>
	INVENTORY => System Manufacturer <Dell Inc.>, System Model <Latitude E7250>, System S/N <5BP4662>, Bios Manufacturer <Dell Inc.>, Bios Date <01/09/2015>, Bios Version <A07>
	INVENTORY => 1 processor(s) Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz [2 core(s) x86_64] at 2301 MHz
	INVENTORY => OS Memory 3497 MB, OS Swap size 6991 MB
	INVENTORY => 2 memory slot(s) found
	INVENTORY => 2 input device(s) found
	INVENTORY => 20 system port(s) found
	INVENTORY => 5 system slot(s) found
	INVENTORY => 4 system controler(s) found
	INVENTORY => 1 storage peripheral(s) found
	INVENTORY => 1 sound device(s) found
	INVENTORY => 1 modem(s) found
	INVENTORY => 6 network adapter(s) found
	INVENTORY => 3 system printer(s) found
	INVENTORY => 1 video adapter(s) found
	INVENTORY => 1 system monitor(s) found
	INVENTORY => Default IPv4 address is <10.1.10.68>
	INVENTORY => Registered company <FLORETTE>, registered owner <FLORETTE>, Product ID <55041-00...>
	INVENTORY => Product key <MAK or V...>
	INVENTORY => 379 software found
	INVENTORY => Computer/VM UUID is <4C4C4544-0042-5010-8034-B5C04F363632>
	INVENTORY => Computer seems to be physical host
	INVENTORY => Bogus summed Memory Slots, 4096 is too far from 3497 (keeping the last one)
	INVENTORY => Reading last inventory state
	EXECUTABLE PLUGIN => Searching for VBS script(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
	EXECUTABLE PLUGIN => Found executable plugin <msofficekey.vbs>
================= TRACE START ===============

================= TRACE STOP ===============
	EXECUTABLE PLUGIN => Plugin <msofficekey.vbs> executed successfully
	EXECUTABLE PLUGIN => Found executable plugin <services.vbs>
================= TRACE START ===============

================= TRACE STOP ===============
	EXECUTABLE PLUGIN => Plugin <services.vbs> executed successfully
	EXECUTABLE PLUGIN => Found executable plugin <uptime.vbs>
================= TRACE START ===============

================= TRACE STOP ===============
	EXECUTABLE PLUGIN => Plugin <uptime.vbs> executed successfully
	EXECUTABLE PLUGIN => Found executable plugin <winusers.vbs>
================= TRACE START ===============

================= TRACE STOP ===============
	EXECUTABLE PLUGIN => Plugin <winusers.vbs> executed successfully
	EXECUTABLE PLUGIN => Searching for executable(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
AGENT => Sending Inventory
	INVENTORY => Checking last inventory state
	INVENTORY => Registry inventory state changed
	INVENTORY => Logical drives inventory state changed
	INVENTORY => Software inventory state changed
INVENTORY => Inventory changed since last run
	INVENTORY => Generating XML document with Device properties
	INVENTORY => XML Update BIOS
	INVENTORY => XML Update 1 CPU(s)
	INVENTORY => XML Update 2 Memory Slot(s)
	INVENTORY => XML Update 2 Input Device(s)
	INVENTORY => XML Update 20 System Port(s)
	INVENTORY => XML Update 4 System Controler(s)
	INVENTORY => XML Update 5 System Slot(s)
	INVENTORY => XML Update 1 Sound Device(s)
	INVENTORY => XML Update 1 Storage Peripheral(s)
	INVENTORY => XML Update 2 Logical Drive(s)
	INVENTORY => XML Update 1 Modem(s)
	INVENTORY => XML Update 6 Network Adapter(s)
	INVENTORY => XML Update 1 Video Adapter(s)
	INVENTORY => XML Update 1 Monitor(s)
	INVENTORY => XML Update 3 Printer(s)
	INVENTORY => XML Update 380 Software
	INVENTORY => XML Update 0 Registry Value(s)
	INVENTORY => XML Update Administrative Information(s)
	INVENTORY => XML Update common Device properties
	LOCAL => Writing compressed XML file <C:\ProgramData\OCS Inventory NG\Agent\PO-DEP2-2016-02-18-13-05-03.ocs> required by argument /LOCAL
================= TRACE START ===============
<?xml version="1.0" encoding="UTF-8"?>

<REPLY>
<RESPONSE>SEND</RESPONSE>
</REPLY>


================= TRACE STOP ===============
AGENT => Inventory successfully sent
	INVENTORY => Writing new inventory state
	WARNING *** INVENTORY => Failed to write new inventory state to file <C:\ProgramData\OCS Inventory NG\Agent\last_state>
	AGENT => Writing standard XML file <C:\ProgramData\OCS Inventory NG\Agent\PO-DEP2-2016-02-18-13-05-03.xml> required by argument /XML
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:29.

**Comment by gillesdubois** [comment]
> AGENT => Local mode actived by /LOCAL argument: No network connection

Si vous lancez l'agent en mode en /LOCAL celui-ci ne transmettera pas son agent au serveur.
Pouvez-vous envoyer un xml de votre inventaire ?

**Comment by headquaker** [comment]
[PO-DEP2-2016-02-18-13-05-03.txt](https://github.com/PluginsOCSInventory-NG/uptime/files/136390/PO-DEP2-2016-02-18-13-05-03.txt)

J'ai mis ca en txt.

**Comment by headquaker** [comment]
En fait il n'y a aucun des autres plugins qui fonctionne.
Uniquement Office (bien qu'il manque des infos par rapport à avant) et Winusers.

**Comment by gillesdubois** [comment]
Avec quel paramètres lancez-vous l'agent pour effectuer l'inventaire ?
Est-ce que la date du dernier inventaire se met a jour sur le ocsreports ?
Car si la machine remonte les info d'un plugin elle devrait remonter les autres sans problèmes.

**Comment by headquaker** [comment]
17h11 le dernier inventaire. Les infos ne remontent pas. :(

**Comment by gillesdubois** [comment]
Pourriez-vous répondre a toutes les questions que je pose ?
1. Avec quel paramètres lancez-vous l'agent pour effectuer l'inventaire ?

**Comment by headquaker** [comment]
/S /SERVER=%OCSSERVER%/ocsinventory /NOSPLASH /DEBUG /NOW /no_systray /TAG=xxx

**Comment by gillesdubois** [comment]
D'accord, cela ne vient pas de l'agent donc ... Pourriez-vous faire isoler quels sont les plugins qui pose problèmes ?
Car dans le cas présent on ne sait pas quel plugin est en cause dans la mesure ou vous en avez plusieurs sur le même agent.
De plus, pourriez-vous vérifier que vos logs d'agent ocs ne comportent pas d'erreur ? (prolog / envoie de l'inventaire)

**Comment by headquaker** [comment]
Bonjour,

J'ai déjà fait cela en n'activant qu'un seul plugin et cela ne change rien.
Actuellement il n'y a que le Winusers et office qui fonctionnent.

**Comment by headquaker** [comment]
Je vais tester en repartant de 0 pour voir.

**Comment by headquaker** [comment]
En fait, tout ce qui est nouveau en terme de plugins ne fonctionne pas.
Avant j'avais winusers et office et ça ça marche.
J'installe les plugins via l'interface : NOK.

**Comment by headquaker** [comment]
Bonjour,

J'ai trouvé. L'installation ne fait que mettre les fichiers au bon endroit mais ne modifie en aucun cas  le fichier MAP et autre. Du coup, aucune remontée dans la BDD.

**Comment by headquaker** [comment]
Il y a pas mal de coquilles un peu partout.

Le code pour le plugin service dans Map.pm est tagé comme étant le plugin UPTIME par exemple.

**Comment by headquaker** [comment]
J'ai cette erreur aussi:

Warning: include(plugins/computer_detail//cd_service/cd_service.php) [function.include]: failed to open stream: No such file or directory in C:\xampp\htdocs\ocs\plugins\main_sections\ms_computer\ms_computer.php on line 203

Warning: include() [function.include]: Failed opening 'plugins/computer_detail//cd_service/cd_service.php' for inclusion (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\ocs\plugins\main_sections\ms_computer\ms_computer.php on line 203

**Comment by gillesdubois** [comment]
https://github.com/PluginsOCSInventory-NG/services/blob/master/APACHE/Map.pm => comme vous pouvez le voir le map.pm de services est bien nommé service et non UPTIME.

Je vais faire les tests de mon côté sur les plugins quevous avez nommé défailliant et vous fait un retour sur leur bon fonctionnement ou non.

**Comment by headquaker** [comment]
Je parlais du commentaire :)

**Comment by headquaker** [comment]
Il y a un problème dans le cd_config.txt.
pour cd_service, il manque des s du coup la mage ne charge pas.

**Comment by headquaker** [comment]
Dans la base j'ai des ? à la place des accents pour les services.

**Comment by gillesdubois** [comment]
Il n'y a pas de cd_config.txt dans la nouvelle version de ocs inventory ... ce fichier a été supprimé et remplacé par un nouveau fichier en xml ... avez-vous bien fait votre mise a jour vers ocs 2.2 ?

**Comment by headquaker** [comment]
je teste sur deux versions en //
En tout cas sur la 2.2. J'ai beau repartir de 0, je n'ai rien qui remonte.

**Comment by gillesdubois** [comment]
La meilleur chose a faire serait d'attendre la documentation du moteur de plugin ... il se peut que certaines choses ne sont pas correctement configurée sur votre ocs.
De plus la documentation apportera des reponses basiques sur les erreurs et problèmes que l'on peux rencontrer.

Cela évitera de faire deux fois le même discours.

Cordialement,
Gilles Dubois.

**Comment by headquaker** [comment]
Dommage d'avoir livrée la 2.2 si vite du coup :)
