### ISSUE TITLE
Remonter d'information

### ISSUE THREAD

**Issue by aze789** [PluginsOCSInventory-NG/uptime#11]
Bonjour, 
Apres avoir installer le plugin comme specifier, je n'arrive pas a avoir la remonter des informations. Comment cela se fait-il ???

**Comment by aze789** [comment]
up

**Comment by gillesdubois** [comment]
Bonjour,

Pour pouvoir aider, nous avons besoin de plus d'informations.
Qu'avez vous fait ? Des logs d'erreurs ont-ils été généré sur le serveur ? Quels tests avez-vous effectué ? 

A savoir que vous êtes sur github et donc c'est la communauté (des volontaires) qui aide, ces personnes ayant souvent un boulot et autre a côté ne pourront pas vous répondre en moins d'une journée.

Cordialement,
Gilles Dubois.

**Comment by aze789** [comment]
C'est bon j'ai trouver la solution.
Merci quand même pour votre aide :)
