### ISSUE TITLE
perl Missing operator

### ISSUE THREAD

**Issue by CyberAbwehr** [PluginsOCSInventory-NG/uptime#18]
perl modules.conf
Number found where operator expected at /usr/local/share/perl/5.30.0/Ocsinventory/Agent/Modules/Uptime.pm line 53, near "$^0"
	(Missing operator before 0?)
syntax error at /usr/local/share/perl/5.30.0/Ocsinventory/Agent/Modules/Uptime.pm line 53, near "$^0"
Can't redeclare "my" in "my" at /usr/local/share/perl/5.30.0/Ocsinventory/Agent/Modules/Uptime.pm line 55, near "my"
syntax error at /usr/local/share/perl/5.30.0/Ocsinventory/Agent/Modules/Uptime.pm line 57, near "} else"
Can't redeclare "my" in "my" at /usr/local/share/perl/5.30.0/Ocsinventory/Agent/Modules/Uptime.pm line 60, near "my"
syntax error at /usr/local/share/perl/5.30.0/Ocsinventory/Agent/Modules/Uptime.pm line 67, near "}"
Can't redeclare "my" in "my" at /usr/local/share/perl/5.30.0/Ocsinventory/Agent/Modules/Uptime.pm line 71, near "my"
syntax error at /usr/local/share/perl/5.30.0/Ocsinventory/Agent/Modules/Uptime.pm line 105, near "}"
Compilation failed in require at modules.conf line 9.
BEGIN failed--compilation aborted at modules.conf line 9.

Client information
plugin: uptime 2.1
ocsinventory-agent --version
Ocsinventory unified agent for UNIX, Linux and MacOSX (2.9.0)

Server information
PHP Version : 7.4.3
Web Server : Apache/2.4.41 (Ubuntu)
Database Server : (Ubuntu) version 8.0.29-0ubuntu0.20.04.3
Version OCSReports: 2.9.1

**Comment by lenicodev** [comment]
just replace the figure 0 by the letter O

**Comment by ad-mcas** [comment]
This bug was patched by merge request #17 on 2022 but there are no new release of this plugin.
This plugin is no longer maintained ?

**Comment by fbomj** [comment]
Uptime v2.2 published
