### ISSUE TITLE
I cant get data from database to ocs console. Please suggest.

### ISSUE THREAD

**Issue by bharanirajendran** [PluginsOCSInventory-NG/uptime#4]

**Comment by gillesdubois** [comment]
Hi @bharanirajendran ,

I need more information on your server / log ?
Did u have error log on plugin install ?

Which ocs version are you using ? Is there any error message displayed on install ?

Regards,
Gilles Dubois.

**Comment by bharanirajendran** [comment]
Hi gillesdubois.

I found errors then resolved. Now its working fine with some clients.
Plugins installed and working really great in OCSinventory 2.3.0RC1 with same version agent. Thanks!

I need help for creating or share plugin for..
     1.  Windows Remote desktop status. If enabled, List of users will display.
     2. List of domain users who is added in Administrator group.

Please share or guide me. 

Regards
Baranidharan R

**Comment by fbomj** [comment]
As there is no more answer I close the issue
