### ISSUE TITLE
problems to install

### ISSUE THREAD

**Issue by fpusersuggest** [PluginsOCSInventory-NG/uptime#6]
Hi,
I have installed the uptime plugin, but I've the following error:
![schermata da 2017-05-09 10-17-25](https://cloud.githubusercontent.com/assets/6614719/25841563/dedf358a-34a0-11e7-8d88-982529172b90.png)

I have **CentOS Linux release 7.3.1611**
my repos are: _epel_, _remi_, _ocsinventory_
The agents installed are 2.3.0 and the ocs **server is 2.3.1** from repo.
I have the same issue with an other plugin: "security" exactly same error. And I have not other plugins installed. After installation I have restarted httpd but no other check I've done.
Thenk you for help.

**Comment by steph78630** [comment]
Hi,

for uptime plugin, check for the presence and rights of the uptime.conf and Map.pm files on your OCS server at :

/etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/Uptime/Map.pm
/etc/ocsinventory-server/plugins/uptime.conf

For another plugin, do the same but with the folders and names of plugins concerned.

Regards, Stéphane
